'use client';

import { useCallback, useMemo } from 'react';
import type { SystemService } from '../types';

interface ToolCanvasProps {
  title: string;
  services: SystemService[];
  network: string;
  volumeDriver: string;
  type: string;
  canvasRef?: React.RefObject<HTMLDivElement | null>;
}

const dockerComposeTemplate = (title: string, services: SystemService[], network: string, volumeDriver: string) => `# Generated by System Config Builder
version: '3.8'

services:
  ${services.map((s) => `  ${s.name}:
    image: ${s.image}
    ports:
      - ${s.ports?.join(', ')}
    volumes:
      ${s.volumes?.map((v) => `      - ${v}`).join('\n      ')}
    depends_on:
      ${s.dependsOn?.map((d) => `        - ${d}`).join('\n      ')}
    networks:
      - ${network}
    `).join('')}
networks:
  default:
    driver: ${network}

volumes:
  ${volumeDriver}`;

const dockerfileTemplate = (title: string, _services: SystemService[]) => `# Generated by System Config Builder
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
`;

const systemdTemplate = (title: string, _services: SystemService[]) => `# Generated by System Config Builder
[Unit]
Description=${title} Service

[Service]
ExecStart=/usr/bin/docker compose up -d
Restart=on-failure
RestartSec=5
Environment="DOCKER_HOST=unix:///var/run/docker.sock"

[Install]
WantedBy=multi-user.target
`;

export function ToolCanvas({ title, services, network, volumeDriver, type }: ToolCanvasProps) {
  const generateOutput = useCallback(() => {
    if (type === 'dockerfile') {
      return dockerfileTemplate(title, services);
    }
    return dockerComposeTemplate(title, services, network, volumeDriver);
  }, [title, services, network, volumeDriver, type]);

  const output = useMemo(() => generateOutput(), [generateOutput]);

  return (
    <div className="config-canvas" role="application" aria-label="System Config Builder">
      <div className="config-section">
        <h3>Configuration Preview</h3>
        <pre
          className="config-preview"
          aria-live="polite"
          style={{
            fontFamily: 'ui-monospace, Menlo, Monaco, monospace',
            fontSize: '0.8125rem',
            padding: '0.75rem',
            background: 'var(--muted-bg)',
            borderRadius: 'var(--radius)',
            overflow: 'auto',
            whiteSpace: 'pre-wrap',
            wordBreak: 'break-word',
          }}
        >
          {output}
        </pre>
      </div>
    </div>
  );
}
