"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { SystemService } from "../types";
import { configTypeLabels } from "../types";

/** Props for the ToolCanvas component. */
interface ToolCanvasProps {
  title: string;
  services: SystemService[];
  network: string;
  volumeDriver: string;
  type: string;
  canvasRef?: React.RefObject<HTMLDivElement | null>;
  onCopy?: () => void;
  onDownload?: () => void;
}

/** Generate Docker Compose YAML from service definitions. */
function generateDockerCompose(
  title: string,
  services: SystemService[],
  network: string,
  volumeDriver: string,
): string {
  // Collect unique named volumes from all services
  const namedVolumes = new Set<string>();
  for (const s of services) {
    if (s.volumes) {
      for (const vol of s.volumes) {
        const parts = vol.split(":");
        // Named volume (e.g. "pgdata:/path") vs bind mount ("/host:/container")
        if (
          parts[0] &&
          !parts[0].startsWith("/") &&
          !parts[0].startsWith(".")
        ) {
          namedVolumes.add(parts[0]);
        }
      }
    }
  }

  const lines: string[] = [
    `# ${title} — Docker Compose`,
    `# Generated by System Config Builder`,
    "",
    "services:",
  ];

  for (const s of services) {
    lines.push(`  ${s.name}:`);
    lines.push(`    image: ${s.image}`);

    if (network && network !== "bridge") {
      lines.push(`    networks:`);
      lines.push(`      - ${network}`);
    }

    if (s.ports && s.ports.length > 0) {
      lines.push("    ports:");
      for (const port of s.ports) {
        // Support optional host:container port mapping via "host:container" format
        if (typeof port === "string" && port.includes(":")) {
          lines.push(`      - "${port}"`);
        } else {
          lines.push(`      - "${port}:${port}"`);
        }
      }
    }

    if (s.volumes && s.volumes.length > 0) {
      lines.push("    volumes:");
      for (const vol of s.volumes) {
        lines.push(`      - ${vol}`);
      }
    }

    if (s.environment && Object.keys(s.environment).length > 0) {
      lines.push("    environment:");
      for (const [key, val] of Object.entries(s.environment)) {
        lines.push(`      ${key}: ${val}`);
      }
    }

    if (s.dependsOn && s.dependsOn.length > 0) {
      lines.push("    depends_on:");
      for (const dep of s.dependsOn) {
        lines.push(`      - ${dep}`);
      }
    }

    if (s.restart) {
      lines.push(`    restart: ${s.restart}`);
    }

    if (s.containerName) {
      lines.push(`    container_name: ${s.containerName}`);
    }

    if (s.labels && Object.keys(s.labels).length > 0) {
      lines.push("    labels:");
      for (const [key, val] of Object.entries(s.labels)) {
        lines.push(`      ${key}: "${val}"`);
      }
    }

    lines.push("");
  }

  if (network && network !== "bridge") {
    lines.push("networks:");
    lines.push(`  ${network}:`);
    lines.push(`    driver: ${network === "custom-net" ? "bridge" : network}`);
    lines.push("");
  }

  if (namedVolumes.size > 0) {
    lines.push("volumes:");
    for (const volName of namedVolumes) {
      lines.push(`  ${volName}:`);
      if (volumeDriver !== "local") {
        lines.push(`    driver: ${volumeDriver}`);
      }
    }
    lines.push("");
  }

  return lines.join("\n");
}

/** Generate a multi-stage Dockerfile for Node.js 22 Alpine. */
function generateDockerfile(title: string): string {
  return [
    `# ${title} — Dockerfile`,
    `# Generated by System Config Builder`,
    "",
    "# ---- Build Stage ----",
    "FROM node:22-alpine AS builder",
    "",
    "WORKDIR /app",
    "",
    "COPY package*.json ./",
    "RUN npm ci",
    "",
    "COPY . .",
    "",
    "# ---- Production Stage ----",
    "FROM node:22-alpine AS runner",
    "",
    "WORKDIR /app",
    "",
    "# Copy only production dependencies from builder",
    "COPY --from=builder /app/package*.json ./",
    "COPY --from=builder /app/node_modules ./node_modules",
    "COPY --from=builder /app .",
    "",
    "ENV NODE_ENV=production",
    "",
    "EXPOSE 3000",
    "",
    'CMD ["node", "dist/index.js"]',
    "",
  ].join("\n");
}

/** Generate a systemd unit file for containerized apps. */
function generateSystemd(title: string): string {
  return [
    `# ${title} — systemd Unit`,
    "# Generated by System Config Builder",
    "",
    "[Unit]",
    `Description=${title} Service`,
    "After=network.target",
    "",
    "[Service]",
    "Type=simple",
    "ExecStart=/usr/bin/docker compose up -d",
    "ExecStop=/usr/bin/docker compose down",
    "Restart=on-failure",
    "RestartSec=5",
    "User=root",
    "Group=root",
    "WorkingDirectory=/opt/app",
    "",
    "[Install]",
    "WantedBy=multi-user.target",
    "",
  ].join("\n");
}

/** Generate an NGINX virtual host config with proxy pass for the primary service.
 * Handles HTTP (port 80) and HTTPS (port 443) detection from service ports.
 * Uses the primary service's first port for proxy_pass. */
function generateNginx(title: string, services: SystemService[]): string {
  const lines: string[] = [
    `# ${title} — NGINX Configuration`,
    "# Generated by System Config Builder",
    "",
  ];

  const primaryService = services[0];

  if (primaryService) {
    const rawPort = primaryService.ports?.[0] || 80;
    // Extract the container port from "host:container" syntax
    const port =
      typeof rawPort === "string" && rawPort.includes(":")
        ? parseInt(rawPort.split(":").pop()!, 10) || 80
        : Number(rawPort) || 80;
    const hasHttps = primaryService.ports?.some((p) => {
      const pNum =
        typeof p === "string" && p.includes(":")
          ? parseInt(p.split(":").pop()!, 10)
          : Number(p);
      return pNum === 443;
    });

    if (hasHttps) {
      lines.push(
        "server {",
        "    listen 443 ssl;",
        `    server_name ${title}.example.com;`,
        "",
        "    ssl_certificate /etc/ssl/certs/example.com.pem;",
        "    ssl_certificate_key /etc/ssl/private/example.com.key;",
        "",
        "    location / {",
        `        proxy_pass http://localhost:${port};`,
        "        proxy_set_header Host $host;",
        "        proxy_set_header X-Real-IP $remote_addr;",
        "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
        "        proxy_set_header X-Forwarded-Proto $scheme;",
        "    }",
        "",
        "    location /static/ {",
        "        alias /var/www/static/;",
        "        expires 30d;",
        "    }",
        "}",
        "",
        "# HTTP redirect to HTTPS",
        "server {",
        "    listen 80;",
        `    server_name ${title}.example.com;`,
        "",
        "    return 301 https://$server_name$request_uri;",
        "}",
      );
    } else {
      lines.push(
        "server {",
        "    listen 80;",
        `    server_name ${title}.example.com;`,
        "",
        "    location / {",
        `        proxy_pass http://localhost:${port};`,
        "        proxy_set_header Host $host;",
        "        proxy_set_header X-Real-IP $remote_addr;",
        "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
        "        proxy_set_header X-Forwarded-Proto $scheme;",
        "    }",
        "",
        "    location /static/ {",
        "        alias /var/www/static/;",
        "        expires 30d;",
        "    }",
        "}",
      );
    }
  } else {
    lines.push(
      "server {",
      "    listen 80;",
      "    server_name _;",
      "",
      "    root /var/www/html;",
      "    index index.html index.htm;",
      "}",
    );
  }

  lines.push("");
  return lines.join("\n");
}

/** Generate a WireGuard VPN peer configuration template. */
function generateWireguard(title: string): string {
  return [
    `# ${title} — WireGuard Configuration`,
    "# Generated by System Config Builder",
    "",
    "[Interface]",
    "Address = 10.0.0.1/24",
    "PrivateKey = <server-private-key>",
    "ListenPort = 51820",
    "",
    "# Replace with your client configuration",
    "[Peer]",
    "# Client 1",
    "PublicKey = <client-public-key>",
    "AllowedIPs = 10.0.0.2/32",
    "",
    "[Peer]",
    "# Client 2",
    "PublicKey = <client-public-key>",
    "AllowedIPs = 10.0.0.3/32",
    "",
  ].join("\n");
}

/** Generate Supervisor config with one program per service. */
function generateSupervisor(title: string, services: SystemService[]): string {
  const lines: string[] = [
    `; ${title} — Supervisor Configuration`,
    "; Generated by System Config Builder",
    "",
    "[supervisord]",
    "nodaemon=true",
    "logfile=/var/log/supervisor/supervisord.log",
    "pidfile=/var/run/supervisord.pid",
    "",
  ];

  for (const s of services) {
    lines.push(`[program:${s.name}]`);
    lines.push(`command=/usr/local/bin/${s.name}`);
    lines.push(`directory=/opt/${s.name}`);
    lines.push("autostart=true");
    lines.push("autorestart=true");
    lines.push("startretries=3");
    lines.push("stderr_logfile=/var/log/supervisor/%(program_name)s.err.log");
    lines.push("stdout_logfile=/var/log/supervisor/%(program_name)s.out.log");
    lines.push(`user=root`);
    lines.push("");
  }

  return lines.join("\n");
}

/** Generate Traefik dynamic YAML config with routers and load-balancer services.
 * Detects HTTPS services (443 port) and configures TLS routes accordingly. */
function generateTraefik(title: string, services: SystemService[]): string {
  const lines: string[] = [
    `# ${title} — Traefik Dynamic Configuration`,
    "# Generated by System Config Builder",
    "",
    "# Static configuration (traefik.yml):",
    "# entryPoints:",
    "#   web:",
    "#     address: ':80'",
    "#   websecure:",
    "#     address: ':443'",
    "# providers:",
    "#   file:",
    "#     filename: /etc/traefik/dynamic.yml",
    "# api:",
    "#   dashboard: true",
    "",
    "---",
    "## HTTP Routers",
    "http:",
    "  routers:",
  ];

  for (const s of services) {
    const hasHttps = s.ports?.some((p) => {
      const pNum =
        typeof p === "string" && p.includes(":")
          ? parseInt(p.split(":").pop()!, 10)
          : Number(p);
      return pNum === 443;
    });

    // Always add HTTP router
    lines.push(`    ${s.name}-http:`);
    lines.push(`      rule: "Host(\`${s.name}.example.com\`)"`);
    lines.push(`      service: ${s.name}`);
    if (hasHttps) {
      lines.push("      middlewares:");
      lines.push("        - https-redirect");
    }
    lines.push("      entryPoints:");
    lines.push("        - web");
    lines.push("");

    if (hasHttps) {
      // Add HTTPS router with TLS
      lines.push(`    ${s.name}-https:`);
      lines.push(`      rule: "Host(\`${s.name}.example.com\`)"`);
      lines.push(`      service: ${s.name}`);
      lines.push("      tls: {}");
      lines.push("      entryPoints:");
      lines.push("        - websecure");
      lines.push("");
    }
  }

  if (
    services.some((s) =>
      s.ports?.some((p) => {
        const pNum =
          typeof p === "string" && p.includes(":")
            ? parseInt(p.split(":").pop()!, 10)
            : Number(p);
        return pNum === 443;
      }),
    )
  ) {
    lines.push("  middlewares:");
    lines.push("    https-redirect:");
    lines.push("      redirectScheme:");
    lines.push("        scheme: https");
    lines.push("        permanent: true");
    lines.push("");
  }

  lines.push("  services:");
  for (const s of services) {
    const rawPort = s.ports?.[0] || 80;
    const port =
      typeof rawPort === "string" && rawPort.includes(":")
        ? parseInt(rawPort.split(":").pop()!, 10) || 80
        : Number(rawPort) || 80;
    lines.push(`    ${s.name}:`);
    lines.push("      loadBalancer:");
    lines.push("        servers:");
    lines.push(`          - url: "http://localhost:${port}/"`);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Route config type to the appropriate generator function.
 *
 * @param type - The configuration type key
 * @param title - Application title for comment headers
 * @param services - Array of service definitions
 * @param network - Docker network name
 * @param volumeDriver - Docker volume driver
 * @returns Generated configuration text
 */
function generateConfig(
  type: string,
  title: string,
  services: SystemService[],
  network: string,
  volumeDriver: string,
): string {
  switch (type) {
    case "docker-compose":
      return generateDockerCompose(title, services, network, volumeDriver);
    case "dockerfile":
      return generateDockerfile(title);
    case "systemd":
      return generateSystemd(title);
    case "nginx":
      return generateNginx(title, services);
    case "wireguard":
      return generateWireguard(title);
    case "supervisor":
      return generateSupervisor(title, services);
    case "traefik":
      return generateTraefik(title, services);
    default:
      return `# Unsupported configuration type: ${type}\n`;
  }
}

/**
 * Map config type to the correct file extension for downloads.
 *
 * @param configType - The configuration type key
 * @returns File extension string (without leading dot)
 */
function getFileExtension(configType: string): string {
  switch (configType) {
    case "docker-compose":
      return "compose.yml";
    case "dockerfile":
      return "Dockerfile";
    case "systemd":
      return "service";
    case "nginx":
      return "conf";
    case "wireguard":
      return "conf";
    case "supervisor":
      return "ini";
    case "traefik":
      return "yml";
    default:
      return "txt";
  }
}

/**
 * ToolCanvas displays the generated configuration output and provides
 * copy-to-clipboard and download actions.
 */
export function ToolCanvas({
  title,
  services,
  network,
  volumeDriver,
  type,
  canvasRef,
  onCopy,
  onDownload,
}: ToolCanvasProps) {
  const output = useMemo(
    () => generateConfig(type, title, services, network, volumeDriver),
    [type, title, services, network, volumeDriver],
  );

  const [copyFeedback, setCopyFeedback] = useState(false);
  const [downloadFeedback, setDownloadFeedback] = useState(false);
  const copyTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const downloadTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    // Cleanup timers on unmount
    return () => {
      if (copyTimerRef.current) clearTimeout(copyTimerRef.current);
      if (downloadTimerRef.current) clearTimeout(downloadTimerRef.current);
    };
  }, []);

  const handleCopy = useCallback(() => {
    if (navigator.clipboard) {
      navigator.clipboard
        .writeText(output)
        .then(() => {
          setCopyFeedback(true);
          if (copyTimerRef.current) clearTimeout(copyTimerRef.current);
          copyTimerRef.current = setTimeout(() => setCopyFeedback(false), 2000);
        })
        .catch(() => {});
    }
  }, [output]);

  const handleDownload = useCallback(() => {
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const ext = getFileExtension(type);
    a.download =
      ext === "Dockerfile"
        ? "Dockerfile"
        : `${title.replace(/[^a-zA-Z0-9_-]/g, "_")}.${ext}`;
    a.click();
    setDownloadFeedback(true);
    if (downloadTimerRef.current) clearTimeout(downloadTimerRef.current);
    downloadTimerRef.current = setTimeout(() => {
      setDownloadFeedback(false);
      URL.revokeObjectURL(url);
    }, 3000);
  }, [output, type, title]);

  const servicesEmpty = services.length === 0;

  return (
    <div ref={canvasRef}>
      <div
        className="config-canvas"
        role="application"
        aria-label="System Config Builder"
      >
        <div className="config-section">
          <div className="config-type-badge">
            ⚙️ {configTypeLabels[type as keyof typeof configTypeLabels] || type}
          </div>
        </div>
        <div className="config-section">
          <h3>Configuration Preview</h3>
          {servicesEmpty ? (
            <div className="config-empty-state" role="status">
              <span className="config-empty-icon">📝</span>
              <p>No services defined yet.</p>
              <p className="config-empty-hint">
                Add a service using the sidebar to generate your configuration.
              </p>
            </div>
          ) : (
            <pre className="config-preview" aria-live="polite" tabIndex={0}>
              {output}
            </pre>
          )}
        </div>
        <div className="config-actions">
          <button
            type="button"
            className={`config-btn config-btn-sm ${copyFeedback ? "config-btn-copied" : "config-btn-primary"}`}
            onClick={onCopy || handleCopy}
            aria-label="Copy configuration to clipboard"
            aria-live={copyFeedback ? "assertive" : undefined}
            disabled={servicesEmpty}
            aria-disabled={servicesEmpty}
            title={servicesEmpty ? "Add a service first" : "Copy to clipboard"}
          >
            {copyFeedback ? "✅ Copied!" : "📋 Copy"}
          </button>
          <button
            type="button"
            className={`config-btn config-btn-secondary config-btn-sm ${downloadFeedback ? "config-btn-downloaded" : ""}`}
            onClick={onDownload || handleDownload}
            aria-label="Download configuration file"
            disabled={servicesEmpty}
            aria-disabled={servicesEmpty}
            title={
              servicesEmpty
                ? "Add a service first"
                : "Download configuration file"
            }
          >
            {downloadFeedback ? "✅ Downloaded!" : "⬇️ Download"}
          </button>
        </div>
      </div>
    </div>
  );
}

ToolCanvas.displayName = "ToolCanvas";
