"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { SystemService } from "../types";
import { configTypeLabels } from "../types";

interface ToolCanvasProps {
  title: string;
  services: SystemService[];
  network: string;
  volumeDriver: string;
  type: string;
  canvasRef?: React.RefObject<HTMLDivElement | null>;
  onCopy?: () => void;
  onDownload?: () => void;
}

/**
 * Generates a Docker Compose YAML configuration string from the given parameters.
 */
function generateDockerCompose(
  title: string,
  services: SystemService[],
  network: string,
  volumeDriver: string,
): string {
  const lines: string[] = [
    `# ${title} — Docker Compose`,
    `# Generated by System Config Builder`,
    "",
    "services:",
  ];

  for (const s of services) {
    lines.push(`  ${s.name}:`);
    lines.push(`    image: ${s.image}`);

    if (s.ports && s.ports.length > 0) {
      lines.push("    ports:");
      for (const port of s.ports) {
        lines.push(`      - "${port}:${port}"`);
      }
    }

    if (s.volumes && s.volumes.length > 0) {
      lines.push("    volumes:");
      for (const vol of s.volumes) {
        lines.push(`      - ${vol}`);
      }
    }

    if (s.environment && Object.keys(s.environment).length > 0) {
      lines.push("    environment:");
      for (const [key, val] of Object.entries(s.environment)) {
        lines.push(`      ${key}: ${val}`);
      }
    }

    if (s.dependsOn && s.dependsOn.length > 0) {
      lines.push("    depends_on:");
      for (const dep of s.dependsOn) {
        lines.push(`      - ${dep}`);
      }
    }

    if (s.restart) {
      lines.push(`    restart: ${s.restart}`);
    }

    lines.push("");
  }

  if (network !== "bridge") {
    lines.push("networks:");
    lines.push(`  ${network}:`);
    lines.push(`    driver: ${network}`);
    lines.push("");
  }

  if (volumeDriver !== "local") {
    lines.push("volumes:");
    lines.push(`  ${volumeDriver}:`);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Generates a basic Dockerfile template.
 */
function generateDockerfile(title: string): string {
  return [
    `# ${title} — Dockerfile`,
    `# Generated by System Config Builder`,
    "",
    "FROM node:18-alpine AS base",
    "",
    "WORKDIR /app",
    "",
    "COPY package*.json ./",
    "RUN npm ci --only=production",
    "",
    "COPY . .",
    "",
    "EXPOSE 3000",
    "",
    'CMD ["npm", "start"]',
    "",
  ].join("\n");
}

/**
 * Generates a systemd unit file template.
 */
function generateSystemd(title: string): string {
  return [
    `# ${title} — systemd Unit`,
    "# Generated by System Config Builder",
    "",
    "[Unit]",
    `Description=${title} Service`,
    "After=network.target",
    "",
    "[Service]",
    "Type=simple",
    "ExecStart=/usr/bin/docker compose up -d",
    "ExecStop=/usr/bin/docker compose down",
    "Restart=on-failure",
    "RestartSec=5",
    "User=root",
    "Group=root",
    "WorkingDirectory=/opt/app",
    "",
    "[Install]",
    "WantedBy=multi-user.target",
    "",
  ].join("\n");
}

/**
 * Generates an NGINX configuration with proxy pass for the first defined service.
 */
function generateNginx(title: string, services: SystemService[]): string {
  const lines: string[] = [
    `# ${title} — NGINX Configuration`,
    "# Generated by System Config Builder",
    "",
  ];

  const primaryService = services[0];

  if (primaryService) {
    const port = primaryService.ports?.[0] || 80;
    lines.push("server {");
    lines.push("    listen 80;");
    lines.push(`    server_name ${title}.example.com;`);
    lines.push("");
    lines.push("    location / {");
    lines.push(`        proxy_pass http://localhost:${port};`);
    lines.push("        proxy_set_header Host $host;");
    lines.push("        proxy_set_header X-Real-IP $remote_addr;");
    lines.push(
      "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
    );
    lines.push("        proxy_set_header X-Forwarded-Proto $scheme;");
    lines.push("    }");
    lines.push("");
    lines.push("    location /static/ {");
    lines.push("        alias /var/www/static/;");
    lines.push("        expires 30d;");
    lines.push("    }");
    lines.push("}");
  } else {
    lines.push("server {");
    lines.push("    listen 80;");
    lines.push("    server_name _;");
    lines.push("");
    lines.push("    root /var/www/html;");
    lines.push("    index index.html index.htm;");
    lines.push("}");
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Generates a WireGuard VPN configuration template.
 */
function generateWireguard(title: string): string {
  return [
    `# ${title} — WireGuard Configuration`,
    "# Generated by System Config Builder",
    "",
    "[Interface]",
    "Address = 10.0.0.1/24",
    "PrivateKey = <server-private-key>",
    "ListenPort = 51820",
    "",
    "# Replace with your client configuration",
    "[Peer]",
    "# Client 1",
    "PublicKey = <client-public-key>",
    "AllowedIPs = 10.0.0.2/32",
    "",
    "[Peer]",
    "# Client 2",
    "PublicKey = <client-public-key>",
    "AllowedIPs = 10.0.0.3/32",
    "",
  ].join("\n");
}

/**
 * Generates a Supervisor program configuration for each defined service.
 */
function generateSupervisor(title: string, services: SystemService[]): string {
  const lines: string[] = [
    `; ${title} — Supervisor Configuration`,
    "; Generated by System Config Builder",
    "",
    "[supervisord]",
    "nodaemon=true",
    "logfile=/var/log/supervisor/supervisord.log",
    "pidfile=/var/run/supervisord.pid",
    "",
  ];

  for (const s of services) {
    lines.push(`[program:${s.name}]`);
    lines.push(`command=/usr/local/bin/${s.name}`);
    lines.push(`directory=/opt/${s.name}`);
    lines.push("autostart=true");
    lines.push("autorestart=true");
    lines.push("startretries=3");
    lines.push("stderr_logfile=/var/log/supervisor/%(program_name)s.err.log");
    lines.push("stdout_logfile=/var/log/supervisor/%(program_name)s.out.log");
    lines.push(`user=root`);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Generates a Traefik reverse proxy configuration (TOML) for each defined service.
 */
function generateTraefik(title: string, services: SystemService[]): string {
  const lines: string[] = [
    `# ${title} — Traefik Configuration`,
    "# Generated by System Config Builder",
    "",
    "## Static Configuration",
    "[entryPoints]",
    "  [entryPoints.web]",
    '    address = ":80"',
    "",
    "  [entryPoints.websecure]",
    '    address = ":443"',
    "",
    "[providers]",
    "  [providers.docker]",
    "    exposedByDefault = false",
    "",
    "[api]",
    "  dashboard = true",
    "",
    "## Dynamic Configuration",
    "[http.routers]",
  ];

  for (const s of services) {
    lines.push(`  [http.routers.${s.name}]`);
    lines.push(`    rule = "Host(\`${s.name}.example.com\`)"`);
    lines.push(`    service = "${s.name}"`);
    lines.push(`    [http.routers.${s.name}.tls]`);
    lines.push("");
  }

  lines.push("[http.services]");
  for (const s of services) {
    const port = s.ports?.[0] || 80;
    lines.push(`  [http.services.${s.name}.loadBalancer.servers]`);
    lines.push(`    url = "http://localhost:${port}"`);
    lines.push("");
  }

  return lines.join("\n");
}

function generateConfig(
  type: string,
  title: string,
  services: SystemService[],
  network: string,
  volumeDriver: string,
): string {
  switch (type) {
    case "docker-compose":
      return generateDockerCompose(title, services, network, volumeDriver);
    case "dockerfile":
      return generateDockerfile(title);
    case "systemd":
      return generateSystemd(title);
    case "nginx":
      return generateNginx(title, services);
    case "wireguard":
      return generateWireguard(title);
    case "supervisor":
      return generateSupervisor(title, services);
    case "traefik":
      return generateTraefik(title, services);
    default:
      return `# Unsupported configuration type: ${type}\n`;
  }
}

function getFileExtension(configType: string): string {
  switch (configType) {
    case "docker-compose":
      return "compose.yml";
    case "dockerfile":
      return "Dockerfile";
    case "systemd":
      return "service";
    case "nginx":
      return "conf";
    case "wireguard":
      return "conf";
    case "supervisor":
      return "ini";
    case "traefik":
      return "toml";
    default:
      return "txt";
  }
}

/**
 * ToolCanvas displays the generated configuration output and provides
 * copy-to-clipboard and download actions.
 */
export function ToolCanvas({
  title,
  services,
  network,
  volumeDriver,
  type,
  canvasRef,
  onCopy,
  onDownload,
}: ToolCanvasProps) {
  const output = useMemo(
    () => generateConfig(type, title, services, network, volumeDriver),
    [type, title, services, network, volumeDriver],
  );

  const [copyFeedback, setCopyFeedback] = useState(false);
  const [downloadFeedback, setDownloadFeedback] = useState(false);
  const copyTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const downloadTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    // Cleanup timers on unmount
    return () => {
      if (copyTimerRef.current) clearTimeout(copyTimerRef.current);
      if (downloadTimerRef.current) clearTimeout(downloadTimerRef.current);
    };
  }, []);

  const handleCopy = useCallback(() => {
    if (navigator.clipboard) {
      onCopy?.();
      navigator.clipboard
        .writeText(output)
        .then(() => {
          setCopyFeedback(true);
          if (copyTimerRef.current) clearTimeout(copyTimerRef.current);
          copyTimerRef.current = setTimeout(() => setCopyFeedback(false), 2000);
        })
        .catch(() => {});
    }
  }, [output, onCopy]);

  const handleDownload = useCallback(() => {
    onDownload?.();
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const ext = getFileExtension(type);
    a.download =
      ext === "Dockerfile"
        ? "Dockerfile"
        : `${title.replace(/[^a-zA-Z0-9_-]/g, "_")}.${ext}`;
    a.click();
    setDownloadFeedback(true);
    if (downloadTimerRef.current) clearTimeout(downloadTimerRef.current);
    downloadTimerRef.current = setTimeout(() => setDownloadFeedback(false), 2000);
    // Revoke the URL after a short delay to ensure the download starts
    requestAnimationFrame(() => URL.revokeObjectURL(url));
  }, [output, type, title, onDownload]);

  const servicesEmpty = services.length === 0;

  return (
    <div ref={canvasRef}>
      <div
        className="config-canvas"
        role="application"
        aria-label="System Config Builder"
      >
        <div className="config-section">
          <div className="config-type-badge">
            ⚙️ {configTypeLabels[type as keyof typeof configTypeLabels] || type}
          </div>
        </div>
        <div className="config-section">
          <h3>Configuration Preview</h3>
          {servicesEmpty ? (
            <div className="config-empty-state" role="status">
              <span className="config-empty-icon">📝</span>
              <p>No services defined yet.</p>
              <p className="config-empty-hint">
                Add a service using the sidebar to generate your configuration.
              </p>
            </div>
          ) : (
            <pre className="config-preview" aria-live="polite" tabIndex={0}>
              {output}
            </pre>
          )}
        </div>
        <div className="config-actions">
          <button
            type="button"
            className={`config-btn config-btn-sm ${copyFeedback ? "config-btn-copied" : "config-btn-primary"}`}
            onClick={onCopy || handleCopy}
            aria-label="Copy configuration to clipboard"
            aria-live={copyFeedback ? "assertive" : undefined}
            disabled={servicesEmpty}
            aria-disabled={servicesEmpty}
            title={servicesEmpty ? "Add a service first" : "Copy to clipboard"}
          >
            {copyFeedback ? "✅ Copied!" : "📋 Copy"}
          </button>
          <button
            type="button"
            className={`config-btn config-btn-secondary config-btn-sm ${downloadFeedback ? "config-btn-downloaded" : ""}`}
            onClick={onDownload || handleDownload}
            aria-label="Download configuration file"
            disabled={servicesEmpty}
            aria-disabled={servicesEmpty}
            title={servicesEmpty ? "Add a service first" : "Download configuration file"}
          >
            {downloadFeedback ? "✅ Downloaded!" : "⬇️ Download"}
          </button>
        </div>
      </div>
    </div>
  );
}
